name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
       ref: learn_ec2
      with:
       ssh-private-key: ${{ secrets.my_ec2_access }}
    - name: Run a one-line script
       run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        #echo ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws --version
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy application on the public ec2 instance
      run:  |
         ls -l
         mkdir ec2_deploy
         cd ec2_deploy
         pwd
         eval `ssh-agent`
         scp -r . ec2-user@ec2-34-201-21-165.compute-1.amazonaws.com:/home/ec2-user/
